vich_uploader:
  db_driver: orm

  mappings:
    formation_images:
      uri_prefix: "%formation_images%"
      upload_destination: "%kernel.project_dir%/public%formation_images%"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
